// Generated by LiveScript 1.2.0
(function(){
  var mainCtrl;
  mainCtrl = function($scope, $http, $interval){
    $scope.data = [];
    $scope.update = function(){
      $http.get("http://ecfa.speaking.tw/json.php", function(json){
        console.log(json);
        return $scope.data = json;
      });
    };
    return $interval($scope.update, 10000);
  };
}).call(this);
