// Generated by LiveScript 1.2.0
(function(){
  $(function(){
    var update;
    update = function(){
      $.getJSON("http://ecfa.speaking.tw/json.php", function(json){
        return console.log(json);
      });
    };
    return setinterval(update, 10000);
  });
}).call(this);
