// Generated by LiveScript 1.2.0
var mainCtrl;
mainCtrl = function($scope, $http, $timeout){
  $scope.data = [];
  $scope.update = function(){
    $http.get("http://ecfa.speaking.tw/json.php", function(json){
      console.log(json);
      for(key of json)
      {
        $scope.data.unshift(json[key]);
      }
      $timeout($scope.update,5000);
    });
  };
  $scope.update();
};
